[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "openai==1.55.1",
    "pandas==2.2.3",
    "regex==2024.11.6",
]
